name: ECPolice
description: Adds more functionality to Drugsforme and Drugsseized plugin.
author: Emil Ekstrom aka Uncle_Emil. On bukkit forums known as Ekstemi
website: http://ekstemicraft.com
softdepend: [TagAPI]
loadbefore: [TagAPI]

main: com.ekstemicraft.plugin.ecpolice.ECPolice
version: 1.0
commands:
    policeman:
        description: Policeman.
        usage: /<command>
  